-- v8: policy_decisions audit hardening (AI-P1-7, INFRA-1B.3.h3-audit-hardening).
-- AC-032 / NFR-008 — extends the audit ledger hook landed in v7 (INFRA-1B.3.x-audit)
-- with DB-level enum enforcement + attempted/outcome correlation.
--
-- Three concerns:
--
-- 1. intended_action enum trigger (BEFORE INSERT) — TypeScript enum
--    (utils/enums.INTENDED_ACTION) is enforced at code boundary, but a raw
--    SQL caller / future script / test setup / manual repair could insert
--    an unknown value. DB-level CHECK via trigger closes the schema gap.
--    Currently the enum has one value ('r2_upload'); designed to extend
--    cleanly when a second intended_action lands.
--
-- 2. r2_upload decision enum trigger (BEFORE INSERT) — same defense-in-depth
--    for the decision column WHEN intended_action='r2_upload'. The
--    operator-policy-gate rows (intended_action IS NULL) keep their existing
--    free-form decision semantics; the r2_upload audit rows are constrained
--    to the 4-value lifecycle (attempted / uploaded / skipped_toctou /
--    set_r2_key_failed_neo4j).
--
-- 3. upload_attempt_id column + index — correlates the BEFORE 'attempted'
--    row with its AFTER outcome row (uploaded / skipped_toctou /
--    set_r2_key_failed_neo4j) for a single r2Put call. Without this,
--    operator audit queries `JOIN ... ON snap_id` rely on rationale text
--    parsing or chronological ordering — brittle when concurrent r2Put
--    calls land for the same snap_id (dedup back-fill race).
--    Generated by snapshot-fingerprint as `uatt_<ULID>` before the attempted
--    insert + reused for the outcome insert.

-- Step 3: upload_attempt_id column + index
ALTER TABLE policy_decisions ADD COLUMN upload_attempt_id TEXT;

CREATE INDEX IF NOT EXISTS policy_decisions_upload_attempt_id_idx
  ON policy_decisions(upload_attempt_id)
  WHERE upload_attempt_id IS NOT NULL;

-- Step 1: intended_action enum trigger.
-- NULL is allowed (operator-policy-gate rows from ADR-0017 keep their semantics).
-- Non-NULL must be in the enum set. Defense-in-depth for future runtime drift.
CREATE TRIGGER IF NOT EXISTS policy_decisions_intended_action_enum_ins
BEFORE INSERT ON policy_decisions
FOR EACH ROW
WHEN NEW.intended_action IS NOT NULL
     AND NEW.intended_action NOT IN ('r2_upload')
BEGIN
  SELECT RAISE(ABORT,
    'policy_decisions.intended_action: invalid value (must be NULL or in INTENDED_ACTION enum: r2_upload)');
END;

-- Step 2: r2_upload decision enum trigger.
-- Fires only when intended_action='r2_upload'; operator-gate rows
-- (intended_action IS NULL) keep their existing decision flexibility.
CREATE TRIGGER IF NOT EXISTS policy_decisions_r2_upload_decision_enum_ins
BEFORE INSERT ON policy_decisions
FOR EACH ROW
WHEN NEW.intended_action = 'r2_upload'
     AND NEW.decision NOT IN (
       'attempted',
       'uploaded',
       'skipped_toctou',
       'set_r2_key_failed_neo4j'
     )
BEGIN
  SELECT RAISE(ABORT,
    'policy_decisions.decision: invalid value for intended_action=r2_upload (must be in R2_UPLOAD_DECISION enum)');
END;

-- Step 1b: r2_upload rows must have a non-empty upload_attempt_id (correlation key).
-- Defense against future caller that forgets the correlation argument —
-- without it, operator audit queries cannot pair BEFORE / AFTER rows
-- across concurrent r2Put calls for the same snap_id.
--
-- Codex PR #49 P2 fix: rejects NULL OR empty/whitespace-only string. The
-- migration explicitly defends against runtime drift / raw SQL / future
-- scripts, and "" is a common "missing value" representation that would
-- silently collapse multiple attempts onto a single non-meaningful key
-- (operator audit query `WHERE upload_attempt_id = ''` would then return
-- ALL drift-affected attempts together — false correlation).
CREATE TRIGGER IF NOT EXISTS policy_decisions_r2_upload_attempt_id_required_ins
BEFORE INSERT ON policy_decisions
FOR EACH ROW
WHEN NEW.intended_action = 'r2_upload'
     AND (NEW.upload_attempt_id IS NULL
          OR TRIM(NEW.upload_attempt_id, ' ' || char(9) || char(10) || char(13)) = '')
BEGIN
  SELECT RAISE(ABORT,
    'policy_decisions.upload_attempt_id: required when intended_action=r2_upload (must be non-empty correlation key for attempted/outcome pair)');
END;

-- Schema version record
INSERT OR IGNORE INTO schema_migrations (version, description)
VALUES ('v8', 'INFRA-1B.3.h3-audit-hardening — policy_decisions enum triggers + upload_attempt_id correlation (AI-P1-7)');
